### ISSUE TITLE
Módulo regex_featurizer não encontrado

### ISSUE THREAD

**Issue by pablodiegoss** [lappis-unb/rasa-ptbr-boilerplate#139]
**Descreva o bug**
Ao utilizar a nova versão lançada, no `make first-run` ou logo depois com `make run-webchat` o container bot morre com o seguinte erro:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/rasa/nlu/registry.py", line 146, in get_component_class
    return class_from_module_path(component_name)
  File "/usr/local/lib/python3.6/site-packages/rasa/utils/common.py", line 174, in class_from_module_path
    m = importlib.import_module(module_name)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'rasa.nlu.featurizers.sparse_featurizer'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/rasa", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/rasa/__main__.py", line 76, in main
    cmdline_arguments.func(cmdline_arguments)
  File "/usr/local/lib/python3.6/site-packages/rasa/cli/run.py", line 119, in run
    rasa.run(**vars(args))
  File "/usr/local/lib/python3.6/site-packages/rasa/run.py", line 56, in run
    **kwargs
  File "/usr/local/lib/python3.6/site-packages/rasa/core/run.py", line 199, in serve_application
    backlog=int(os.environ.get("SANIC_BACKLOG", "100")),
  File "/usr/local/lib/python3.6/site-packages/sanic/app.py", line 1096, in run
    serve(**server_settings)
  File "/usr/local/lib/python3.6/site-packages/sanic/server.py", line 742, in serve
    trigger_events(before_start, loop)
  File "/usr/local/lib/python3.6/site-packages/sanic/server.py", line 604, in trigger_events
    loop.run_until_complete(result)
  File "uvloop/loop.pyx", line 1417, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.6/site-packages/rasa/core/run.py", line 241, in load_agent_on_start
    action_endpoint=endpoints.action,
  File "/usr/local/lib/python3.6/site-packages/rasa/core/agent.py", line 261, in load_agent
    remote_storage=remote_storage,
  File "/usr/local/lib/python3.6/site-packages/rasa/core/agent.py", line 912, in load_local_model
    remote_storage=remote_storage,
  File "/usr/local/lib/python3.6/site-packages/rasa/core/agent.py", line 373, in load
    interpreter = NaturalLanguageInterpreter.create(nlu_model)
  File "/usr/local/lib/python3.6/site-packages/rasa/core/interpreter.py", line 57, in create
    return RasaNLUInterpreter(model_directory=obj)
  File "/usr/local/lib/python3.6/site-packages/rasa/core/interpreter.py", line 263, in __init__
    self._load_interpreter()
  File "/usr/local/lib/python3.6/site-packages/rasa/core/interpreter.py", line 286, in _load_interpreter
    self.interpreter = Interpreter.load(self.model_directory)
  File "/usr/local/lib/python3.6/site-packages/rasa/nlu/model.py", line 305, in load
    return Interpreter.create(model_metadata, component_builder, skip_validation)
  File "/usr/local/lib/python3.6/site-packages/rasa/nlu/model.py", line 327, in create
    components.validate_requirements(model_metadata.component_classes)
  File "/usr/local/lib/python3.6/site-packages/rasa/nlu/components.py", line 38, in validate_requirements
    component_class = registry.get_component_class(component_name)
  File "/usr/local/lib/python3.6/site-packages/rasa/nlu/registry.py", line 174, in get_component_class
    raise Exception(exception_message)
Exception: Failed to find module 'rasa.nlu.featurizers.sparse_featurizer.regex_featurizer'. 
No module named 'rasa.nlu.featurizers.sparse_featurizer'
make: *** [Makefile:49: webchat] Error 1
```

Resumindo: 
```
Exception: Failed to find module 'rasa.nlu.featurizers.sparse_featurizer.regex_featurizer'. 
No module named 'rasa.nlu.featurizers.sparse_featurizer'
```
**Para reproduzir o bug**
1. Limpe suas imagens docker
2. Execute o `make first-run`
3. docker ps -a
4. docker logs <id do container bot que estará com exit>

**Ambiente:**
 - SO: Lubuntu 19.10

**Comment by arthurTemporim** [comment]
Seu projeto aparentemente está utilizando o `python 3.6` porém a configuração atual utiliza o python-3.7 como base:
[docker-requirements](https://github.com/lappis-unb/rasa-ptbr-boilerplate/blob/6c20bdd89dca8a6468668df0d2a884b4fa8f0a63/docker/requirements.Dockerfile#L1) será que não é configuração antiga?

**Comment by pablodiegoss** [comment]
Aparentemente eu não limpei os containeres antigos do projeto e a versão nova estava rodando no python-3.6 como você disse e quebrando... apagar todos os meus containeres e buildar tudo dnv resolveu!
