### ISSUE TITLE
make validate - Could not load dynamic library 'libcudart.so.10.1'; 

### ISSUE THREAD

**Issue by silvagpe** [lappis-unb/rasa-ptbr-boilerplate#205]
**Descreva o bug**
Quando executo o comando make validate na pasta /bot é apresentada a excessão abaixo

``` 
$(venv) home/projetos/rasa-ptbr-boilerplate/bot$ make validate 
rasa data validate 		\
	-v

---------------------------------------------------------------------------------------------------------------------------------------------

2021-04-30 11:25:13.352280: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2021-04-30 11:25:13.352321: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "/home/silva/project/rasa/rasa-ptbr-boilerplate/venv/bin/rasa", line 5, in <module>
    from rasa.__main__ import main
  File "/home/silva/project/rasa/rasa-ptbr-boilerplate/venv/lib/python3.7/site-packages/rasa/__init__.py", line 9, in <module>
    from rasa.train import train
  File "/home/silva/project/rasa/rasa-ptbr-boilerplate/venv/lib/python3.7/site-packages/rasa/train.py", line 39, in <module>
    from rasa.core.agent import Agent
  File "/home/silva/project/rasa/rasa-ptbr-boilerplate/venv/lib/python3.7/site-packages/rasa/core/agent.py", line 15, in <module>
    from rasa.core.channels.channel import OutputChannel, UserMessage
  File "/home/silva/project/rasa/rasa-ptbr-boilerplate/venv/lib/python3.7/site-packages/rasa/core/channels/__init__.py", line 12, in <module>
    from rasa.core.channels.socketio import SocketIOInput
  File "/home/silva/project/rasa/rasa-ptbr-boilerplate/venv/lib/python3.7/site-packages/rasa/core/channels/socketio.py", line 10, in <module>
    from socketio import AsyncServer
  File "/home/silva/project/rasa/rasa-ptbr-boilerplate/venv/lib/python3.7/site-packages/socketio/__init__.py", line 3, in <module>
    from .client import Client
  File "/home/silva/project/rasa/rasa-ptbr-boilerplate/venv/lib/python3.7/site-packages/socketio/client.py", line 11, in <module>
    from . import packet
  File "/home/silva/project/rasa/rasa-ptbr-boilerplate/venv/lib/python3.7/site-packages/socketio/packet.py", line 2, in <module>
    from engineio import json as _json
ImportError: cannot import name 'json' from 'engineio' (/home/silva/project/rasa/rasa-ptbr-boilerplate/venv/lib/python3.7/site-packages/engineio/__init__.py)
make: *** [Makefile:48: validate] Error 1

---------------------------------------------------------------------------------------------------------------------------------------------
``` 

**Para reproduzir o bug**
Passo-a-passo para reproduzir o comportamento do bug:

1) git clone https://github.com/lappis-unb/rasa-ptbr-boilerplate.git
2) make first-run
3) cd bot
4) make validate 

**Comportamento esperado**
...

**Ambiente:**
```
$ neofetch
       _,met$$$$$gg.          silva@lx-i5
    ,g$$$$$$$$$$$$$$$P.       -----------
  ,g$$P"     """Y$$.".        OS: Debian GNU/Linux 10 (buster) x86_64
 ,$$P'              `$$$.     Kernel: 4.19.0-16-amd64
',$$P       ,ggs.     `$$b:   Uptime: 18 mins
`d$$'     ,$P"'   .    $$$    Packages: 1684 (dpkg)
 $$P      d$'     ,    $$P    Shell: bash 5.0.3
 $$:      $$.   -    ,d$$'    Terminal: /dev/pts/0
 $$;      Y$b._   _,d$P'      CPU: Intel i5-2400 (4) @ 3.400GHz
 Y$$.    `.`"Y$$$$P"'         GPU: NVIDIA GeForce GT 730
 `$$b      "-.__              Memory: 670MiB / 16006MiB
  `Y$$
   `Y$$.
     `$$b.
       `Y$$b.
          `"Y$b._
              `"""

```

Obrigado, 
Se eu encontrar a solução complemento aqui na issue para servir de referência para outras pessoas.

**Comment by silvagpe** [comment]
Para conseguir executar sem dar erro foi necessário adicionar o rasa-sdk~=2.4.0 no arquivo de requirements.txt

Arquivo final
```
rasa==2.4.1
nltk==3.4.5
rasa-sdk~=2.4.0
elasticsearch==7.0.4
```

O erro do cuda permanece mas não impede que o rasa funcione.
