### ISSUE TITLE
ImportError: cannot import name 'json' from 'engineio'

### ISSUE THREAD

**Issue by mirellef** [lappis-unb/rasa-ptbr-boilerplate#207]
**Descreva o bug**
Apos executar sudo make first-run os conteiner para como seguinte erro 

````
Traceback (most recent call last):
  File "/usr/local/bin/rasa", line 5, in <module>
    from rasa.__main__ import main
  File "/usr/local/lib/python3.7/site-packages/rasa/__init__.py", line 9, in <module>
    from rasa.train import train
  File "/usr/local/lib/python3.7/site-packages/rasa/train.py", line 39, in <module>
    from rasa.core.agent import Agent
  File "/usr/local/lib/python3.7/site-packages/rasa/core/agent.py", line 15, in <module>
    from rasa.core.channels.channel import OutputChannel, UserMessage
  File "/usr/local/lib/python3.7/site-packages/rasa/core/channels/__init__.py", line 12, in <module>
    from rasa.core.channels.socketio import SocketIOInput
  File "/usr/local/lib/python3.7/site-packages/rasa/core/channels/socketio.py", line 10, in <module>
    from socketio import AsyncServer
  File "/usr/local/lib/python3.7/site-packages/socketio/__init__.py", line 3, in <module>
    from .client import Client
  File "/usr/local/lib/python3.7/site-packages/socketio/client.py", line 11, in <module>
    from . import packet
  File "/usr/local/lib/python3.7/site-packages/socketio/packet.py", line 2, in <module>
    from engineio import json as _json
ImportError: cannot import name 'json' from 'engineio' (/usr/local/lib/python3.7/site-packages/engineio/__init__.py)
make: *** [Makefile:57: shell] Error 1
Makefile:70: recipe for target 'run-shell' failed
make[1]: *** [run-shell] Error 2
make[1]: Leaving directory '/home/vic/BOSS/rasa-ptbr-boilerplate'
Makefile:13: recipe for target 'first-run' failed
make: *** [first-run] Error
````

**Para reproduzir o bug**
Passo-a-passo para reproduzir o comportamento do bug:
1. git clone <Link para o repositório>
2. Exexute o comando make first-run
4. Veja o erro

**Comportamento esperado**
Conseguir subir o projeto.

**Ambiente:**
 - SO: Debian 9 
 - SO: Ubuntu 20.04

**Comment by arthurTemporim** [comment]
Ola @mirellef realmente não está funcionando!

Estou investigando agora, assim que descobrir o problema comento aqui e mando o PR.

Isso mostra que a build não está completa por não apontar esse problema, vou conferir nosso CI também 👌🏽

**Comment by arthurTemporim** [comment]
@mirellef Atualizei o projeto nos PRs #206 e #208. Você pode, por favor, atualizar sua branch `main`e testar novamente o projeto?

Fico no aguardo 😄

**Comment by arthurTemporim** [comment]
Olá, estou fechando esta issue por inatividade, se achar que ainda está com problema, por favor, reabra :D
